import type { AnalysisState } from '../types/analysis';

// export const PSH_DB: Record<string, number> = {
//   Rajasthan: 6.0,
//   Gujarat: 5.8,
//   Maharashtra: 5.5,
//   Karnataka: 5.3,
//   'Tamil Nadu': 5.4,
//   Delhi: 5.2,
//   'West Bengal': 4.8,
//   Kerala: 4.6,
//   Other: 5.0,
// };

export const EUI_DB: Record<string, number> = {
  Residential: 0.13,
  Institutional: 0.41,
  Commercial: 0.71,
  Industry: 0.5,
};

export const AREA_DB: Record<string, number> = {
  Residential: 70,
  Institutional: 150,
  Commercial: 1000,
  Industry: 1000,
};

export const BATTERY_COST_DB: Record<AnalysisState['inputs']['chemistry'], number> = {
  LFP: 18000,
  NMC: 22000,
  'Lead-Acid': 10000,
};

export const STEP_LABELS = [
  'Project',
  'Load',
  'BESS',
  'Solar',
  'CAPEX',
  'Finance',
  'Env',
  'Compare',
  'Report',
];

export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
export const MONTHLY_FACTORS = [1.0, 1.05, 1.1, 1.12, 1.08, 0.95, 0.85, 0.87, 0.9, 1.0, 1.02, 0.98];

export const COLORS = {
  blue: '#00BFFF',
  orange: '#FFA500',
  green: '#22C55E',
  purple: '#A855F7',
  red: '#EF4444',
  gray: '#64748B',
  teal: '#14B8A6',
  yellow: '#EAB308',
};

export const initialState: AnalysisState = {
  step: 0,
  totalSteps: 9,
  loadMethod: 'auto',
  showWizard: false,
  appliances: [
    
    {id: crypto.randomUUID(),name: 'Lighting-corridors-LED', qty: 10, w: 20, hrs: 12,priority:'critical',},
    {id: crypto.randomUUID(),name: 'Lighting-Indoors-LED', qty: 15, w: 20, hrs: 12,priority:'critical', },
    {id: crypto.randomUUID(), name: 'Lightings-Outdoor-LED', qty: 2, w: 150, hrs: 8,priority:'critical', },
    {id: crypto.randomUUID(), name: 'Ceiling Fan', qty:10, w: 50, hrs: 24,priority:'critical', },
    {id: crypto.randomUUID(), name: 'Drinking Water Purifier', qty: 1, w: 50, hrs: 12,priority:'critical', },
    {id: crypto.randomUUID(), name: 'submersible water pump', qty: 1, w: 1500, hrs: 2,priority:'critical', },
    {id: crypto.randomUUID(), name: 'Electronics gadget charging points', qty: 5, w: 30, hrs: 24,priority:'critical', },
    {id: crypto.randomUUID(), name: 'Refrigerators(emergency medicines)(190 Ltr.)', qty: 1, w: 230, hrs: 12,priority:'critical', },
    {id: crypto.randomUUID(), name: 'Fire alarm', qty: 1, w: 150, hrs: 24,priority:'critical', },
    {id: crypto.randomUUID(), name: 'wall mounted fans', qty: 1, w: 50, hrs: 24,priority:'non_critical', },
    {id: crypto.randomUUID(), name: 'Pedestal fans', qty: 5, w: 50, hrs: 24,priority:'non_critical', },
    {id: crypto.randomUUID(),name: 'Cooking Facility(Electric)', qty: 2, w: 1500, hrs: 2 ,priority:'non_critical',},
    {id: crypto.randomUUID(),name: 'Coolers', qty: 1, w: 200, hrs: 8 ,priority:'non_critical',},
    {id: crypto.randomUUID(),name: 'sat. phones(charging)', qty: 1, w: 50, hrs: 12 ,priority:'non_critical',},
  ],
  inputs: {
    projectName: 'My Solar Project',
    locationName: '',
    latitude: 28.6139,
    longitude: 77.2090,
    psh: 5.5,
    averageTemperature: 25,
    evCostOption: 'included',
    systemMode: 'ongrid-rts-bess',
    currency: 'INR',
    tariff: 7.5,
    gridImportTariff: 7.5,
    gridExportTariff: 4.5,
    tariffEscalation: 5,
    discountRate: 10,
    projectLife: 25,
    buildingCategory: 'Commercial',
    eui: 0.71,
    area: 1000,
    occupancyDays: 300,
    billAmount: 25000,
    directDailyKwh: 100,
    directPeakKw: 20,
    lossFactor: 18,
    panelWp: 540,
    panelArea: 2.7,
    solarTimeShare: 40,
    solarCuf: 18,
    batteryChargingRequirement: 0,
    degradation: 0.5,
    roofArea: 500,
    designLoadOverride: 0,
    selfConsumption: 80,
    roofAvailable: 500,
    roofUsablePct: 70,
    roofTilt: 15,
    roofType: 'Flat',
    dod: 92,
    rte: 80,
    chemistry: 'LFP',
    backupHours: 4,
    autonomyHours: 4,
    dailyCycles: 1,
    bessCostKwh: 10000,
    batteryCost: 10000,
    panelCost: 45000,
    inverterCost: 30000,
    mountingCost: 8,
    bosCost: 6,
    installCost: 10,
    monitoringCost: 50000,
    engineeringPct: 3,
    contingencyPct: 5,
    gst: 12,
    subsidy: 0,
    omPct: 1,
    omEscalationRate: 5,
    insurancePct: 0.3,
    exportRate: 4,
    exportPct: 20,
    dgCost: 20,
    vollBenefit: 0,
    evAnnualSavings: 0,
    evPurchaseCost: 1500000,
    chargingInfraCost: 150000,
    netMeteringCost: 50000,
    governmentSubsidy: 'no',
    externalFinancing: 'no',
    loanPct: 70,
    interestRate: 10,
    tenure: 10,
    inflation: 6,
    batteryCoverage :"critical",
    contractDemand: 0,
    dieselPrice: 95,
    vollRate: 100,
    evElectricityCost: 3.5,
    fuelEscalation : 5,
    outageEventsPerYear: 5,
    outageHoursPerEvent: 48,
    predictiveMaintenanceHours: 24,
    dieselConsumptionRate: 0.35,
    dgCapacityMultiplier: 1.8,
    dieselCapacityBump: 1.2,
    dgAnnualMaintenance: 15000,
    evDailyDistance: 90,
    petrolMileage: 10,
    petrolPrice: 105,
    evConsumptionKwhKm: 0.15,
    evOmPct: 1,
    batteryReplacementPct: 80,
    batteryReplacementYear: 11,
    inverterReplacementPct: 80,
    inverterReplacementYear: 11,
    
  },
};
